apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: credit-scoring
data:
  APP_ENV: "staging"
  LOG_LEVEL: "info"
  MODEL_PATH: "/app/models/credit_default_model.pkl"
  DVC_REMOTE: "storage"
  S3_ENDPOINT_URL: "https://storage.yandexcloud.net"
  AWS_REGION: "ru-central1"
  AWS_DEFAULT_REGION: "ru-central1"
  AWS_EC2_METADATA_DISABLED: "true"
